### ISSUE TITLE
bad wallpaper (sorry, russian)

### ISSUE THREAD

**Issue by alex9yust** [Havoc-OS/android_frameworks_base#116]
https://github.com/Havoc-OS/android_frameworks_base/blob/d1c604364b283471b42378ac9bb0881a5566a3eb/packages/SystemUI/src/com/android/systemui/glwallpaper/ImageProcessHelper.java#L134

https://www.ixbt.com/news/2020/05/31/jeti-oboi-ubivajut-smartfony-osobenno-stradajut-telefony-samsung.html

```
 -   int[] histogram = new int[256];
 +   int[] histogram = new int[257];


```y=256
histogram[256] error

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/40f19a7c46dcbd0aec8845236b54de27a551ff3e

**Comment by ValZapod** [comment]
This is wrong fix. LOL. This is just a non standard ProPhoto with different whitepoint.
