### ISSUE TITLE
Java error[Solved]

### ISSUE THREAD

**Issue by y1mz** [Havoc-OS/android_frameworks_base#128]
I getting this error while compliying the source code.
The compling log is in here: https://drive.google.com/file/d/13Bwd2gryNy9Rg0ZMqapYMRSuvW3Z4Qbs/view?usp=sharing
``` FAILED: /home/batuhan/Rom/Sources/havoc-3/out/soong/.intermediates/frameworks/base/framework/android_common/javac/framework.jar15 ```

**Comment by SKULSHADY** [comment]
Please paste the console output in pastebin or del.dog and share the link
