### ISSUE TITLE
Partial screenshot broken

### ISSUE THREAD

**Issue by neekless** [Havoc-OS/android_frameworks_base#27]
Commit https://github.com/Havoc-OS/android_frameworks_base/commit/76e5e4eeace6fd1175629c6b1e16909bdd0d788a breaks partial screenshots.

I think 
`mScreenshotLayout.post(new Runnable() {` 
needs to be changed back to 
`mScreenshotSelectorLayout.post(new Runnable() {`
This commit seems to come from ROMs that don't use ScreenshotSelectorLayout but havoc uses it.

**Comment by VarunS2002** [comment]
@neekless Why did you close this issue its still not fixed please re-open it

**Comment by neekless** [comment]
@gundopanth because it's fixed long ago here https://github.com/Havoc-OS/android_frameworks_base/commit/3ec9f6862a194c67949085aa68a4092d690fd0e2 and I can confirm it's fixed and works. If it doesn't work for you then your device has a problem that is not related to this issue.
