### ISSUE TITLE
Some clocks not updating in AOD

### ISSUE THREAD

**Issue by neekless** [Havoc-OS/android_frameworks_base#33]
In AOD mode, only digital clocks (all styles: bold, accent, accent hour, etc) refresh their time. Using any analog clock or the text clock and the time doesn't refresh in AOD. They refresh normally in the normal lockscreen though. I've been looking through the code trying to pinpoint the problem but I'm still an amateur so I failed. Hopefully you can find the problem.

Edit: It only fails to refresh if unplugged

**Comment by SKULSHADY** [comment]
I'll take a look later

**Comment by neekless** [comment]
Any news on this? If AOD is on and phone goes into deep sleep (doze), analog clocks and Q text clock won't update the time, only digital clocks (all variants including sammy and accents) will update. I've looked through KeyguardStatusView.java but can't find the problem. Really want to use Q text clock but AOD is useless if the time doesn't update lol.

Can you reproduce this problem? Turn AOD on and leave your phone alone let it go into deep sleep for a while and see if your time updates.

**Comment by SKULSHADY** [comment]
No. I can't find the exact cause for it.
