### ISSUE TITLE
Analog Lock Screen Clocks clear the lock screen

### ISSUE THREAD

**Issue by diamondjohndroid** [Havoc-OS/android_frameworks_base#86]
Running Havoc-OS-v2.8-20190908-ks01ltexx-Official.zip but also on my own build around the same time.

If I select any (well at least the 4 or 5 I tried) of the analog clocks under:
Settings/Havoc Settings/Lock Screen/Clock Widget

When I lock the phone and turn it back on, the lock screen is clear apart from notifications, status bar and the lock icon. ie the upper shortcuts, lower shortcuts and the lock clock and weather are not displayed.

From memory, in a previous build I did a few months back, the analog clocks that were available back then, appeared to be working.

**Comment by diamondjohndroid** [comment]
Some screen shots, and my current settings (https://del.dog/hecucuqina.nginx)
Before:
![Screenshot_20190912-113523](https://user-images.githubusercontent.com/30639161/64747325-05a14380-d552-11e9-97e0-7ef84019314b.jpg)

Setting:
![Screenshot_20190912-113604](https://user-images.githubusercontent.com/30639161/64747375-2c5f7a00-d552-11e9-9b3e-fc7ec84499aa.jpg)

After/Result:
![Screenshot_20190912-113556](https://user-images.githubusercontent.com/30639161/64747380-32555b00-d552-11e9-95a4-3ed5098dd2e1.jpg)

**Comment by SKULSHADY** [comment]
Change dpi
