### ISSUE TITLE
After r16 merge torch is broken on 8956\8952 and maybe others

### ISSUE THREAD

**Issue by magicxavi** [Havoc-OS/android_frameworks_base#98]
Here is a log:
12-09 07:39:44.429   513  2277 E CameraService: setTorchMode: Setting torch mode of camera "0" to 1 failed: Not a data message (-74)
12-09 07:39:44.431  3132  3598 E FlashlightController: Couldn't set torch mode
12-09 07:39:44.431  3132  3598 E FlashlightController: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): setTorchMode:1656: Setting torch mode of camera "0" to 1 failed: Not a data message (-74)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:802)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:1096)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.hardware.camera2.CameraManager.setTorchMode(CameraManager.java:638)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at com.android.systemui.statusbar.policy.FlashlightControllerImpl.setFlashlight(FlashlightControllerImpl.java:100)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at com.android.systemui.qs.tiles.FlashlightTile.handleClick(FlashlightTile.java:85)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:500)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.Looper.loop(Looper.java:214)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-09 07:39:44.431  3132  3598 E FlashlightController: Caused by: android.os.ServiceSpecificException: setTorchMode:1656: Setting torch mode of camera "0" to 1 failed: Not a data message (-74) (code 10)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.Parcel.createException(Parcel.java:2085)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.Parcel.readException(Parcel.java:2039)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.os.Parcel.readException(Parcel.java:1987)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.hardware.ICameraService$Stub$Proxy.setTorchMode(ICameraService.java:846)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:1094)
12-09 07:39:44.431  3132  3598 E FlashlightController: 	... 7 more

**Comment by schumacherd** [comment]
On 8976 same issue.

**Comment by Sap1k** [comment]
On a3y17lte it broke the camera completely
dlopen failed: shared library "libgui.so" not found

**Comment by magicxavi** [comment]
It can be fixed in DT.

**Comment by ClintT** [comment]
> It can be fixed in DT.

hi, i have the same problem with bacon. what did you add to your DT to fix the error?

**Comment by Abhi011999** [comment]
@ClintT https://github.com/magicxavi/device_xiaomi_msm8956-common/commit/d8de8c8fa34997975d0ef04b6983e61b45c54797
